version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    networks:
      kafka-net:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    container_name: kafka-broker
    hostname: broker
    networks:
      kafka-net:
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - $KAFKA_SSL_SECRETS_DIR:/etc/kafka/secrets
      - $BOUNCY_CUSTOM_PROVIDER:/usr/share/java/kafka/SecurityCustomProvider.jar
    environment:

      KAFKA_SSL_PROVIDER: BCJSSE
      KAFKA_SECURITY_PROVIDERS: org.upm.tfg.securityCustomProvider.standardProv.BouncyStandardSecurityProvider, org.upm.tfg.securityCustomProvider.sslProv.BouncyJsseSecurityProvider, org.upm.tfg.securityCustomProvider.pqcProv.BouncyPqcSecurityProvider
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.3
      # KAFKA_SSL_ENGINE_FACTORY_CLASS: org.bouncycastle.tls.crypto.impl.bc.BcTlsMLKemDomain
      # KAFKA_SSL_CIPHER_SUITES: Kyber-512
      # ---------Deprecated---------
      # KAFKA_SECURITY_PROVIDERS: org.tfg.upm.bouncyCastle.securityProv.BouncySecurityProvider, org.tfg.upm.bouncyCastle.sslProv.BouncyJsseSecurityProvider, org.tfg.upm.bouncyCastle.pqcProv.BouncyPqcSecurityProvider



      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,SSL://localhost:9093
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_truststore_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: broker.truststore.pkcs12
      KAFKA_SSL_KEYSTORE_FILENAME: broker.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
      KAFKA_SECURITY_PROTOCOL: SSL
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_CLIENT_AUTH: 'required'

      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      # KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G" # Ajusta el tamaño de la memoria heap según tus necesidades
      # KAFKA_OPTS: "-XX:MaxDirectMemorySize=4G"
      # KAFKA_METADATA_MAX_RETENTION_BYTES: "369296129"
      # KAFKA_OFFSETS_TOPIC_SEGMENT_BYTES: "369296129"
      # KAFKA_SOCKET_REQUEST_MAX_BYTES: "369296129"
      # KAFKA_TRANSACTION_STATE_LOG_SEGMENT_BYTES: "369296129"

networks:
  kafka-net: