spring:
    application:
        name: topicDemo
    kafka:
        security:
            protocol: "SSL"
        bootstrap-servers: localhost:9093
        ssl:
            key-password: 123456
            trust-store-location: file:///home/ithaqua/Documents/Kafka/SandBox_Kafka/post-quantum-support-kafka/certificates/clients/client.truststore.pkcs12
            trust-store-password: 123456
            enabled-protocols: TLSv1.3
            endpoint-identification-algorithm:
